<a href="https://colab.research.google.com/github/mitakshra/TensorFlow/blob/main/PyTorchDeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np


In [3]:
torch_2d = torch.randn(2, 3)
print(torch_2d)

tensor([[ 0.0475,  0.9585,  0.9338],
        [ 1.6804,  0.2654, -0.5619]])


In [4]:
import tensorflow as tf
ten = tf.random.normal([2, 3])
print(ten)

tf.Tensor(
[[2.1419213  1.276524   1.6222872 ]
 [1.1573056  0.485964   0.31917274]], shape=(2, 3), dtype=float32)
